### ISSUE TITLE
Onnx output and pytorch output are inconsistent

### ISSUE THREAD

**Issue by SeanLiu081** [andresprados/SPIGA#10]
Thanks  for open-sourcing this great work. I have encountered a problem now. When I convert the model to onnx and tensorrt, the landmark result of trt/onnx  is  different from the result of pytorch model. I find the problem is self.conv_window in onnx，you can see the result before self.conv_window and after self.conv_window. I print the crops[0, :5, :5] before self.conv_window[0] of torch and onnx，they are same,
![image](https://user-images.githubusercontent.com/26735847/235104294-70ea5ac5-4025-4fd3-b4b4-6c11c30c5a3a.png)
![image](https://user-images.githubusercontent.com/26735847/235104395-81296016-35bf-462c-a52d-aa602ba4ba85.png)
After self.conv_window[0]，the visual_fts[0,:5,:5] are different，
![image](https://user-images.githubusercontent.com/26735847/235105279-12527e68-bd7b-4e94-9578-e1d85b8529ab.png)
![image](https://user-images.githubusercontent.com/26735847/235105423-551756b8-171c-4628-a243-74437a08c3a8.png)

**Comment by SeanLiu081** [comment]
the pytorch result :
![image](https://user-images.githubusercontent.com/26735847/235109939-a6bedcd6-c133-4651-8db8-6b329c12ca61.png)
the onnx/tensorrt result:
![image](https://user-images.githubusercontent.com/26735847/235110103-8948c569-a270-4419-989c-6eb15e92acab.png)

**Comment by edmosRovi** [comment]
Hello, I'm interested in how to convert the modelo to ONNX formato. I have try it but my ONNX modelo nota works, fails in the execution. Please could you tell me how do you get the ONNX model??
I opened an issue here but nobody answer me yet:
https://github.com/andresprados/SPIGA/issues/4

**Comment by john09282922** [comment]
Hi, can u share onnx file?

**Comment by lokeycookie** [comment]
@SeanLiu081 
is it possible for you to share what steps you took to generate the onnx files?
