### ISSUE TITLE
Fit FLAME model to Landmarks

### ISSUE THREAD

**Issue by emlcpfx** [andresprados/SPIGA#11]
Does anyone know how to fit the FLAME 3DMM to these landmarks?

I’d be interested in hiring someone who could build something like DECA or 3DDFA_V2 using these landmarks.

**Comment by EvdoTheo** [comment]
> Does anyone know how to fit the FLAME 3DMM to these landmarks?
> 
> I’d be interested in hiring someone who could build something like DECA or 3DDFA_V2 using these landmarks.

Hello @emlcpfx did you find a way to solve this matter?
