### ISSUE TITLE
UnpicklingError: While running in Local and Colab

### ISSUE THREAD

**Issue by mollahmdsaif** [andresprados/SPIGA#22]
While Running demo I am encountering UnpicklingError. I have used latest pytorch and pytorch 1.4. It gave same error. I am encountering this in colab and local machine both.
```
`UnpicklingError                           Traceback (most recent call last)
<ipython-input-3-d26975ab34c8> in <cell line: 10>()
      8 
      9 # Process video
---> 10 video_app(video_path,
     11           spiga_dataset='wflw',               # Choices=['wflw', '300wpublic', '300wprivate', 'merlrav']
     12           tracker='RetinaSort',               # Choices=['RetinaSort', 'RetinaSort_Res50']

5 frames
/usr/local/lib/python3.10/dist-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
   1256             "functionality.")
   1257 
-> 1258     magic_number = pickle_module.load(f, **pickle_load_args)
   1259     if magic_number != MAGIC_NUMBER:
   1260         raise RuntimeError("Invalid magic number; corrupt file?")

UnpicklingError: invalid load key, '<'.`
```

**Comment by aknsubbu** [comment]
I am facing the same issue... Any suggested fixes?

**Comment by Inferencer** [comment]
download the models manually fixed it for me

**Comment by aknsubbu** [comment]
how are you plugging in the modes after downloading it... seems to create problems for me

**Comment by Inferencer** [comment]
> how are you plugging in the modes after downloading it... seems to create problems for me

i put them in a folder called weights
C:\Users\Jack\SPIGA\spiga\models\weights

**Comment by andresprados** [comment]
I have uploaded the models to a [Hugging Face model card](https://huggingface.co/aprados/spiga/tree/main) and the demos should be available again. The problem was somehow related to an incompatibility of the Python version used (above python 3.8), the torch.hub functions used to download the weights and the storage in google drive.
